# Generated by Django 5.2 on 2025-12-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_options_alter_cita_estado_bloqueohorario'),
        ('evaluaciones', '0001_initial'),
        ('usuarios', '0004_alter_paciente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nota_clinica', serialize=False, to='citas.cita', verbose_name='Cita Asociada')),
                ('diagnostico_subjetivo', models.TextField(help_text='Información reportada por el paciente (síntomas, historial, etc.).', verbose_name='Diagnóstico Subjetivo (S)')),
                ('diagnostico_objetivo', models.TextField(help_text='Hallazgos del examen físico (rangos, fuerza, pruebas especiales, etc.).', verbose_name='Diagnóstico Objetivo (O)')),
                ('analisis_y_plan', models.TextField(help_text='Análisis del Kine, objetivos de la sesión y plan de tratamiento futuro.', verbose_name='Análisis y Plan (A/P)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_clinicas_creadas', to='usuarios.kinesiologo', verbose_name='Kinesiólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_clinicas', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Nota Clínica',
                'verbose_name_plural': 'Notas Clínicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
