# Generated by Django 5.2 on 2025-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='sin apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
