# Generated by Django 5.2 on 2025-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_apellido_perfil_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes Médicos Relevantes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('F', 'FONASA'), ('I', 'ISAPRE'), ('P', 'Particular')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
