# Generated by Django 5.2 on 2025-11-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=60)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('AG', 'Agendada'), ('CF', 'Confirmada'), ('CL', 'Cancelada'), ('FN', 'Finalizada')], default='AG', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_atendidas', to='usuarios.kinesiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_solicitadas', to='usuarios.paciente')),
            ],
            options={
                'ordering': ['fecha_hora_inicio'],
                'unique_together': {('kinesiologo', 'fecha_hora_inicio')},
            },
        ),
    ]
