# Generated by Django 5.2 on 2025-12-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('usuarios', '0004_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha_hora_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, help_text='Ej. Vacaciones, Trámites Personales, Conferencia.', max_length=255, null=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='usuarios.kinesiologo')),
            ],
            options={
                'verbose_name': 'Bloqueo de Horario',
                'verbose_name_plural': 'Bloqueos de Horarios',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
